//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        public int CommandeID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> produitID { get; set; }
        public Nullable<int> quantite { get; set; }
        public Nullable<int> total { get; set; }
    }
}
