//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUIT()
        {
            this.COULEUR = new HashSet<COULEUR>();
        }
    
        public int ProduitID { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public Nullable<int> Prix { get; set; }
        public Nullable<int> FournisseurID { get; set; }
        public Nullable<int> CategorieID { get; set; }
    
        public virtual CATEGORIE CATEGORIE { get; set; }
        public virtual FOURNISSEUR FOURNISSEUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COULEUR> COULEUR { get; set; }
    }
}
